# Generated by Django 4.1.4 on 2022-12-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_alter_deliverys_courier_alter_deliverys_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverys',
            name='courier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom.couriers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverys',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.users'),
        ),
    ]
